name = "Sofa"
author = "Doppytoo"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bcb03e9d37e8cdfefeb67b878459820e15f3c442da120582ab903de8192d065"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
