name = "NeoSofa"
author = "Doppytoo"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22d19b9ade7ae3c38d07131b26100548b39c5d9be2ff0ffcfd76bf5e5f89417a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.104"
