name = "Sofa"
author = "Doppytoo"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bce12d7b5855e2dc8027ca957a1ec4cb4651785b34218741d6bb460b7cff24bf"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
