name = "Sofa"
author = "Doppytoo"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22d1a36555dc3b0186190b3dd87866e32ac8cf67d97b8036f00880e40b7fea80"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
